In [1]:
import numpy as np
x = np.array([0.0, 1.0, 2.0, 3.0,  4.0,  5.0])
y = np.array([0.0, 0.8, 0.9, 0.1, -0.8, -1.0])
z = np.polyfit(x, y, 10, full=True)
z

(array([ -7.10087609e-07,  -8.00951219e-07,   8.28398283e-06,
          8.21448395e-05,   4.23627486e-04,   8.77682355e-04,
         -7.04676324e-03,  -7.48012158e-02,  -1.08226791e-01,
          9.88684542e-01,  -7.25194643e-16]),
 array([], dtype=float64),
 6,
 array([ 3.13199928,  0.99844377,  0.41969317,  0.12923531,  0.02877568,
         0.00428572]),
 1.3322676295501878e-15)

In [2]:
xx = np.poly1d(z[0])
(xx(x) - y).var()

4.285523399662682e-29

In [5]:
X = np.column_stack((x, y))
X.shape, X


((6, 2), array([[ 0. ,  0. ],
        [ 1. ,  0.8],
        [ 2. ,  0.9],
        [ 3. ,  0.1],
        [ 4. , -0.8],
        [ 5. , -1. ]]))

In [8]:
a = np.array([[1,2], [3,4]])
for x in a: print (x)

[1 2]
[3 4]


In [12]:
np.histogram(a), np.histogram(np.array([1,2, 3,4]))

((array([1, 0, 0, 1, 0, 0, 1, 0, 0, 1]),
  array([ 1. ,  1.3,  1.6,  1.9,  2.2,  2.5,  2.8,  3.1,  3.4,  3.7,  4. ])),
 (array([1, 0, 0, 1, 0, 0, 1, 0, 0, 1]),
  array([ 1. ,  1.3,  1.6,  1.9,  2.2,  2.5,  2.8,  3.1,  3.4,  3.7,  4. ])))